// user
export const LOGIN_ACTION = 'AppConstants/LOGIN_ACTION';
export const LOGIN_ASYNC_ACTION = 'AppConstants/LOGIN_ASYNC_ACTION';

// services
export const FETCH_SERVICES_ASYNC_ACTION = 'AppConstants/FETCH_SERVICES_ASYNC_ACTION';
export const SET_SERVICES_ACTION = 'AppConstants/SET_SERVICES_ACTION';
export const WRITE_VALUE_TO_CHARACTERISTICS_ASYNC_ACTION = 'AppConstants/WRITE_VALUE_TO_CHARACTERISTICS_ASYNC_ACTION';
export const FETCH_CHARACTERISTICS_FOR_SERVICES_ASYNC_ACTION = 'AppConstants/FETCH_CHARACTERISTICS_FOR_SERVICES_ASYNC_ACTION';
export const SET_CHARACTERISTICS_FOR_SERVICES_ACTION = 'AppConstants/SET_CHARACTERISTICS_FOR_SERVICES_ACTION';

// websockets
export const SUBSCRIBE_FOR_NOTIFICATIONS_ASYNC_ACTION = 'AppConstants/SUBSCRIBE_FOR_NOTIFICATIONS_ASYNC_ACTION';

// api
export const SERVICE_TYPE_LIGHT = 'light';
export const CHARACTERISTICS_IS_ON = 'is_on';